# Generated by Django 3.1 on 2020-09-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='website.review'),
        ),
    ]
