# Generated by Django 3.1 on 2020-08-31 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200831_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.cart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.wishlist'),
        ),
    ]
