# Generated by Django 3.1 on 2020-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200831_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
