# Generated by Django 3.1 on 2020-08-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verication',
            field=models.BooleanField(default=False),
        ),
    ]
