# Generated by Django 3.1 on 2020-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customer_email_verication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='rafimuhammad', max_length=50),
            preserve_default=False,
        ),
    ]
