# Generated by Django 3.1 on 2020-09-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200901_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='this is descriptions', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1, null=True),
        ),
    ]
