# Generated by Django 3.1 on 2020-08-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_customer_email_verication_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_verication_key',
            field=models.CharField(max_length=32),
        ),
    ]
