# Generated by Django 3.1 on 2020-09-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_product_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
