# Generated by Django 3.1 on 2020-08-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200901_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_verication',
            new_name='email_verification',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email_verication_key',
            new_name='email_verification_key',
        ),
    ]
