# Generated by Django 3.1 on 2020-09-03 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200903_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='BQV0GKEP', max_length=50, primary_key=True, serialize=False),
        ),
    ]
