# Generated by Django 3.1 on 2020-09-04 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200903_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ULL7Z6W7', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='customer_cart', to='website.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='website.Cart'),
        ),
    ]
