# Generated by Django 3.1 on 2020-09-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200904_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_cart', to='website.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='HCYLX0JB', max_length=50, primary_key=True, serialize=False),
        ),
    ]
