# Generated by Django 3.1 on 2020-09-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200904_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='DTZZCY2T', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_to_approve', 'Waiting to Approve'), ('waiting_for_payment', 'Waiting for Payment'), ('verified', 'Verified'), ('on_shipping', 'On Shipping'), ('arrived', 'Arrived'), ('finish', 'Finish')], default='waiting_to_approve', max_length=64),
        ),
    ]
